/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    MarkdownEditor: typeof import('./components/MarkdownEditor.vue')['default']
    MarkdownToolbar: typeof import('./components/MarkdownToolbar.vue')['default']
    MermaidRenderer: typeof import('./components/MermaidRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsDialog: typeof import('./components/SettingsDialog.vue')['default']
  }
}
