/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    MarkdownContent: typeof import('./components/cheatsheet/MarkdownContent.vue')['default']
    MarkdownEditor: typeof import('./components/MarkdownEditor.vue')['default']
    MermaidContent: typeof import('./components/cheatsheet/MermaidContent.vue')['default']
    MermaidRenderer: typeof import('./components/MermaidRenderer.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ShortcutsContent: typeof import('./components/cheatsheet/ShortcutsContent.vue')['default']
  }
}
